ALTER TABLE topicos
DROP CONSTRAINT topicos_email_key;

ALTER TABLE topicos
ADD COLUMN fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE topicos
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ABIERTO';